"""rename PeriodicTasks to PeriodicTasksChange

Revision ID: 03993886aba4
Revises: c4778b8a1da9
Create Date: 2021-02-27 18:05:59.201262+08:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from src.libs.sa.timezone import TZDateTime

# revision identifiers, used by Alembic.
revision = "03993886aba4"
down_revision = "c4778b8a1da9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "celery_periodic_tasks_change",
        sa.Column("last_update", TZDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("last_update"),
    )
    op.drop_table("celery_periodic_tasks")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "celery_periodic_tasks",
        sa.Column(
            "last_update", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("last_update", name="celery_periodic_tasks_pkey"),
    )
    op.drop_table("celery_periodic_tasks_change")
    # ### end Alembic commands ###
