"""init

Revision ID: c4778b8a1da9
Revises:
Create Date: 2021-02-23 21:21:54.727392+08:00

"""
from alembic import op
import sqlalchemy as sa
from src.libs.sa.timezone import TZDateTime

# revision identifiers, used by Alembic.
revision = "c4778b8a1da9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "celery_clocked_schedule",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("clocked_time", TZDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "celery_crontab_schedule",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("minute", sa.String(length=240), nullable=False),
        sa.Column("hour", sa.String(length=96), nullable=False),
        sa.Column("day_of_month", sa.String(length=124), nullable=False),
        sa.Column("month_of_year", sa.String(length=64), nullable=False),
        sa.Column("day_of_week", sa.String(length=64), nullable=False),
        sa.Column("timezone", sa.String(length=63), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "celery_interval_schedule",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("every", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=24), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "celery_periodic_tasks",
        sa.Column("last_update", TZDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("last_update"),
    )
    op.create_table(
        "celery_solar_schedule",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event", sa.String(length=24), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event", "latitude", "longitude"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "celery_periodic_task",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("task", sa.String(length=200), nullable=True),
        sa.Column("interval_id", sa.Integer(), nullable=True),
        sa.Column("crontab_id", sa.Integer(), nullable=True),
        sa.Column("clocked_id", sa.Integer(), nullable=True),
        sa.Column("solar_id", sa.Integer(), nullable=True),
        sa.Column("args", sa.Text(), nullable=True),
        sa.Column("kwargs", sa.Text(), nullable=True),
        sa.Column("queue", sa.String(length=200), nullable=True),
        sa.Column("exchange", sa.String(length=200), nullable=True),
        sa.Column("routing_key", sa.String(length=200), nullable=True),
        sa.Column("headers", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("expires", TZDateTime(), nullable=True),
        sa.Column("expire_seconds", sa.Integer(), nullable=True),
        sa.Column("one_off", sa.Boolean(), nullable=False),
        sa.Column("start_time", TZDateTime(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", TZDateTime(), nullable=True),
        sa.Column("total_run_count", sa.Integer(), nullable=False),
        sa.Column("date_changed", TZDateTime(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["clocked_id"],
            ["celery_clocked_schedule.id"],
        ),
        sa.ForeignKeyConstraint(
            ["crontab_id"],
            ["celery_crontab_schedule.id"],
        ),
        sa.ForeignKeyConstraint(
            ["interval_id"],
            ["celery_interval_schedule.id"],
        ),
        sa.ForeignKeyConstraint(
            ["solar_id"],
            ["celery_solar_schedule.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("celery_periodic_task")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("celery_solar_schedule")
    op.drop_table("celery_periodic_tasks")
    op.drop_table("celery_interval_schedule")
    op.drop_table("celery_crontab_schedule")
    op.drop_table("celery_clocked_schedule")
    # ### end Alembic commands ###
